version: "3.8"

services:
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform_env
    working_dir: /app
    volumes:
      - ./:/app  
    env_file:
      - .env  # 
    entrypoint: ["terraform"]  
    command: ["--help"] 

